# rubocop:disable all
# TODO - FIX COP
# rubocop:enable all

inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.4.3
  DisplayStyleGuide: false
  NewCops: enable
  Exclude:
    - '___v3_construction_site__/**/*'
    - 'backup/**/*'
    - 'build/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/*'
    - 'db/fixtures/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'script/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - 'Guardfile'
    - 'tmp.rb'
    - 'scratch.rb'

Style/Documentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Metrics/ClassLength:
  Max: 180

Metrics/MethodLength:
  Max: 16

Layout/LineLength:
  Max: 180
  Exclude:
    - 'lib/tasks/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Enabled: false
